### ISSUE TITLE
Question on create_group()

### ISSUE THREAD

**Issue by Spyop3** [andrewsayre/pyheos#7]
Hello Andrew

I'm using your lib to develop a gnome-extension for controlling my heos

And thanks a lot cause pretty quick I got play/stop working :)

I cannot understand how to use the command create_group() and particulary what is expected in data: dict ?

Can you provide me more explanation please 

pyheos version : 0.4.0
Python version 3.7 
Os: ubuntu

**Comment by andrewsayre** [comment]
`create_group` is only in the dev branch at this moment.  I'm working on some other logic changes and then will release 0.5.0 which will have that later today (hopefully).

The signature is:
```python
async def create_group(self, leader_id: int, member_ids: Sequence[int])
```
- `leader_id` is the `player_id` for the lead player.
- `member_ids` is a sequence of `player_ids` making up the members of the group, other than the leader.

A good place to look for how to use the methods is in the tests.  Everything is fully covered.  Test for this particular method are here: https://github.com/andrewsayre/pyheos/blob/dev/tests/test_heos.py#L768-L774

**Comment by andrewsayre** [comment]
v0.5.0 has been released which includes the group manipulation APIs.
